stages:
  - test
  - static
  - build
  - dockerize
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DOCKER_IMAGE_NAME: "edgebox"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/pip
    - .venv/

.python-base:
  image: python:3.11.7
  before_script:
    - python -V  # Print out python version for debugging
    - pip install --progress-bar off uv  # Install uv
    - uv sync

mypy:
  stage: static
  extends: .python-base
  allow_failure: true
  script:
    - pip install mypy
    - python -m mypy */*.py
  when: manual

flake8:
  stage: static
  extends: .python-base
  allow_failure: true
  script:
    - pip install flake8
    - flake8 --max-line=120 */*.py
  when: manual

pylint:
  stage: static
  extends: .python-base
  allow_failure: true
  script:
    - pip install pylint
    - mkdir ./pylint
    - pylint --output-format=text */*.py | tee ./pylint/pylint.log || pylint-exit $?
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
  when: manual
  artifacts:
    paths:
      - ./pylint/


.docker-base:
  image: docker:20.10.24
  services:
    - docker:20.10.24-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"

test:
  stage: test
  extends: .python-base
  script:
    - uv run python -m unittest

build-package:
  stage: build
  extends: .python-base
  script:
    - uv run python -m build
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz

build-docker:
  stage: dockerize
  extends: .docker-base
  needs: ["build-package"]
  script:
    - echo "Docker Hub Username ${DOCKER_HUB_USERNAME}"
    - docker info
    - docker build -t deleteme .
  when: manual

release-package:
  stage: release
  extends: .python-base
  only:
    - tags
  script:
    - uv run python -m build
    - uv run twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/* -u gitlab-ci-token -p ${CI_JOB_TOKEN}
    - uv run twine upload --repository pypi dist/* -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} --verbose
  when: manual

release-docker:
  stage: release
  extends: .docker-base
  only:
    - tags
  script:
    - echo "Docker Hub Username ${DOCKER_HUB_USERNAME}"
    - docker info
    - docker build -t ${DOCKER_HUB_USERNAME}/${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG} .
    - echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker push ${DOCKER_HUB_USERNAME}/${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
  when: manual
